### ISSUE TITLE
Error while ng build --prod

### ISSUE THREAD

**Issue by naveenrsaradhya** [creativetimofficial/blk-design-system-angular#1]

**Comment by naveenrsaradhya** [comment]
lexical error on line 1: unrecognized text. erroneous area: 1: 100% - $icon-size-xl - 1

**Comment by adonix-dev** [comment]
Making
--
1) `git clone https://github.com/creativetimofficial/blk-design-system-angular.git`
2) `npm install`
3) `ng build --prod`

We get
--
```
Your global Angular CLI version (9.1.5) is greater than your local
version (9.0.5). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
0% compiling
Compiling @angular/core : module as esm5
Compiling @angular/common : module as esm5
Compiling @angular/platform-browser : module as esm5
[...]
Compiling ngx-bootstrap/popover : module as esm5

92% chunk asset optimization optimize-css-webpack-pluginAn unhandled exception occurred: Lexical error on line 1: Unrecognized text.

Erroneous area:
1: 100% - auto - 1
^.........^
See "/tmp/ng-Mlxsci/angular-errors.log" for further details.
```

The tmp file
--
```
[error] JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 100% - auto - 1
^.........^
    at /home/dodle/[MYAPP]/styles.e920f57bfaf203af2e1b.css:14176:3
    at Object.parseError (/home/dodle/[MYAPP]/node_modules/postcss-calc/dist/parser.js:1200:15)
    at Object.lexer_parseError [as parseError] (/home/dodle/[MYAPP]/node_modules/postcss-calc/dist/parser.js:2333:44)
    at Object.lexer_next [as next] (/home/dodle/[MYAPP]/node_modules/postcss-calc/dist/parser.js:3328:22)
    at Object.lexer_fastLex [as fastLex] (/home/dodle/[MYAPP]/node_modules/postcss-calc/dist/parser.js:3403:18)
    at fastLex (/home/dodle/[MYAPP]/node_modules/postcss-calc/dist/parser.js:1603:27)
    at Parser.parse (/home/dodle/[MYAPP]/node_modules/postcss-calc/dist/parser.js:1677:30)
    at /home/dodle/[MYAPP]/node_modules/postcss-calc/dist/lib/transform.js:33:30
    at walk (/home/dodle/[MYAPP]/node_modules/postcss-value-parser/lib/walk.js:7:16)
    at ValueParser.walk (/home/dodle/[MYAPP]/node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (/home/dodle/[MYAPP]/node_modules/postcss-calc/dist/lib/transform.js:24:50)
    at _default (/home/dodle/[MYAPP]/node_modules/postcss-calc/dist/lib/transform.js:66:100)
    at /home/dodle/[MYAPP]/node_modules/postcss-calc/dist/index.js:27:32
    at /home/dodle/[MYAPP]/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/home/dodle/[MYAPP]/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/home/dodle/[MYAPP]/node_modules/postcss/lib/container.js:131:17)
    at /home/dodle/[MYAPP]/node_modules/postcss/lib/container.js:148:24
```

**Comment by rarestoma** [comment]
Hi,

Thank you for working with our products.

Please go to the src/assets/scss/blk-design-system/custom/_icons.scss and replace:

`width: calc(100% - #{$icon-size} - 1);`

with 

`width: calc(100% - #{$icon-size-sm} - 1);`



`width: calc(100% - $icon-size-xl - 1);`

with 

`width: calc(100% - #{$icon-size-xl} - 1);`



 ` width: calc(100% - $icon-size-lg - 1);`

with

`  width: calc(100% - #{$icon-size-lg} - 1);`


`  width: calc(100% - $icon-size-sm - 1);`

with

`  width: calc(100% - #{$icon-size-sm} - 1);`

Please let me know if it works.

Thank you,
Rares

**Comment by adonix-dev** [comment]
Yeaaaaah !! It work !! **You genius ! @rarestoma **
